linters:
  enable:
    - asasalint
    - bidichk
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - forbidigo
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - gosimple
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - typecheck
    - usestdlibvars
    - unparam
    - unused
    - whitespace
